### ISSUE TITLE
Few tasks we need to address

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/vue-handsontable-official#64]
Following the React wrapper success we can use some of those ideas for Vue wrapper too.

- [x] Set `vue-handsontable-official` npm package as deprecated (check angular-handsontable for Readme.md and deprecation message templates).
- [x] `Dist` should have UMD, CommonJS and ES files. We can use Rollup as we did with React wrapper.
- [x] Add Issue template
- [x] Add Pull Request template
- [x] Add missing info to `package.json` #60, #61, #62 
- [x] Use `id` instead `root` and remove `this.` #18 **breaking change**
- [x] Make sure we can pass `id`, `style` and `class` attributes to HoT container
- [x] Add Typescript definition file or "rewrite" to Typescript #25
- [x] Add sourcemaps for `min.(js|css)` files (and `.js` file if we go the Typescript path)
- [x] Fix two remaining bugs #50 and #20
- [x] Check if workaround for  #65 is still needed
